Bump Terraform's azurerm provider to 3.0.0
Azure/Mission-Critical-Online pull request #250
Opened 2022-03-24 16:33 UTC by heoelri

This PR contains required changes required to use the 3.0 version of the Terraform azurerm provider. https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.0.0

E2E testing is running here: https://dev.azure.com/Mission-Critical/Online/_build/results?buildId=773&view=results

Draft PR still work in progress / and needs further testing.

2022-03-25 10:35 UTC, msimecek commented
How about `3.0.1`? ;)

2022-03-25 10:37 UTC, heoelri commented
> How about `3.0.1`? ;)

You're of course right - but I assume the work to do is the same.. ;) Dependabot can take care of 3.0.1 then..

2022-03-25 10:40 UTC, msimecek commented
I know, but especially when the work to do is minimal, I would prefer to update straight to the latest version instead of dealing with the Dependabot overhead in a few weeks...

2022-03-25 10:50 UTC, heoelri commented
> I know, but especially when the work to do is minimal, I would prefer to update straight to the latest version instead of dealing with the Dependabot overhead in a few weeks...

For sure, I was a bit too quick setting this PR to ready for review.. its a rabbit hole..

2022-03-28 08:02 UTC, sebader requested changes

2022-03-28 08:02 UTC, sebader commented on src/infra/monitoring/grafana/terraform/stamps/app-service.tf
> +    #linux_fx_version                        = "DOCKER|${var.wapp_container_image}"
please cleanup if it works

2022-03-28 08:02 UTC, sebader commented on src/testing/userload-generator/infra/modules/regional_function/functionapp.tf
> +    # linux_fx_version = "NODE|14"
clean

2022-03-28 08:27 UTC, heoelri commented
E2E Test is running here: https://dev.azure.com/mission-critical/Online/_build/results?buildId=800&view=results

2022-03-29 08:48 UTC, sebader approved these changes

2022-03-29 08:49 UTC, heoelri commented
Will prepare a PR for -connected in the next hours or days. Would like to keep an eye on this one in -online first.

2022-03-29 08:49 UTC, merged